/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectBranchRouteImport } from './routes/select-branch'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicWarrantyRouteImport } from './routes/_public/warranty'
import { Route as PublicUsedGeneratorsRouteImport } from './routes/_public/used-generators'
import { Route as PublicServiceRequestRouteImport } from './routes/_public/service-request'
import { Route as PublicRentalGeneratorsRouteImport } from './routes/_public/rental-generators'
import { Route as PublicRecommendRouteImport } from './routes/_public/recommend'
import { Route as PublicProductsRouteImport } from './routes/_public/products'
import { Route as PublicDealersRouteImport } from './routes/_public/dealers'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicCompareRouteImport } from './routes/_public/compare'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AppWarrantyAdminRouteImport } from './routes/_app/warranty-admin'
import { Route as AppVendorsRouteImport } from './routes/_app/vendors'
import { Route as AppServiceRouteImport } from './routes/_app/service'
import { Route as AppSalesOrdersRouteImport } from './routes/_app/sales-orders'
import { Route as AppRolesRouteImport } from './routes/_app/roles'
import { Route as AppQuotationsRouteImport } from './routes/_app/quotations'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppPriceListRouteImport } from './routes/_app/price-list'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppEmployeesRouteImport } from './routes/_app/employees'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppCompaniesRouteImport } from './routes/_app/companies'
import { Route as AppBranchesRouteImport } from './routes/_app/branches'
import { Route as AppAuditLogRouteImport } from './routes/_app/audit-log'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports.index'
import { Route as PublicProductsIdRouteImport } from './routes/_public/products.$id'
import { Route as AppSalesDebitNotesRouteImport } from './routes/_app/sales/debit-notes'
import { Route as AppSalesCreditNotesRouteImport } from './routes/_app/sales/credit-notes'
import { Route as AppReportsWarrantyRouteImport } from './routes/_app/reports.warranty'
import { Route as AppReportsServiceRouteImport } from './routes/_app/reports.service'
import { Route as AppReportsSalesRouteImport } from './routes/_app/reports.sales'
import { Route as AppReportsQuotationsRouteImport } from './routes/_app/reports.quotations'
import { Route as AppReportsPurchasesRouteImport } from './routes/_app/reports.purchases'
import { Route as AppReportsProductsRouteImport } from './routes/_app/reports.products'
import { Route as AppReportsOutstandingRouteImport } from './routes/_app/reports.outstanding'
import { Route as AppReportsOrdersRouteImport } from './routes/_app/reports.orders'
import { Route as AppReportsInvoicesRouteImport } from './routes/_app/reports.invoices'
import { Route as AppReportsInventoryRouteImport } from './routes/_app/reports.inventory'
import { Route as AppReportsGstRouteImport } from './routes/_app/reports.gst'
import { Route as AppReportsEmployeesRouteImport } from './routes/_app/reports.employees'
import { Route as AppReportsCustomersRouteImport } from './routes/_app/reports.customers'
import { Route as AppReportsCollectionsRouteImport } from './routes/_app/reports.collections'
import { Route as AppReportsAmcRouteImport } from './routes/_app/reports.amc'
import { Route as AppSalesInvoicesIndexRouteImport } from './routes/_app/sales/invoices.index'
import { Route as AppSalesEstimatesIndexRouteImport } from './routes/_app/sales/estimates.index'
import { Route as AppSalesInvoicesNewRouteImport } from './routes/_app/sales/invoices.new'
import { Route as AppSalesEstimatesNewRouteImport } from './routes/_app/sales/estimates.new'

const SelectBranchRoute = SelectBranchRouteImport.update({
  id: '/select-branch',
  path: '/select-branch',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicWarrantyRoute = PublicWarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => PublicRoute,
} as any)
const PublicUsedGeneratorsRoute = PublicUsedGeneratorsRouteImport.update({
  id: '/used-generators',
  path: '/used-generators',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServiceRequestRoute = PublicServiceRequestRouteImport.update({
  id: '/service-request',
  path: '/service-request',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRentalGeneratorsRoute = PublicRentalGeneratorsRouteImport.update({
  id: '/rental-generators',
  path: '/rental-generators',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRecommendRoute = PublicRecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsRoute = PublicProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDealersRoute = PublicDealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCompareRoute = PublicCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AppWarrantyAdminRoute = AppWarrantyAdminRouteImport.update({
  id: '/warranty-admin',
  path: '/warranty-admin',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceRoute = AppServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersRoute = AppSalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPriceListRoute = AppPriceListRouteImport.update({
  id: '/price-list',
  path: '/price-list',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogRoute = AppAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const PublicProductsIdRoute = PublicProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicProductsRoute,
} as any)
const AppSalesDebitNotesRoute = AppSalesDebitNotesRouteImport.update({
  id: '/sales/debit-notes',
  path: '/sales/debit-notes',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesCreditNotesRoute = AppSalesCreditNotesRouteImport.update({
  id: '/sales/credit-notes',
  path: '/sales/credit-notes',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsWarrantyRoute = AppReportsWarrantyRouteImport.update({
  id: '/reports/warranty',
  path: '/reports/warranty',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsServiceRoute = AppReportsServiceRouteImport.update({
  id: '/reports/service',
  path: '/reports/service',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsSalesRoute = AppReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsQuotationsRoute = AppReportsQuotationsRouteImport.update({
  id: '/reports/quotations',
  path: '/reports/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsPurchasesRoute = AppReportsPurchasesRouteImport.update({
  id: '/reports/purchases',
  path: '/reports/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsProductsRoute = AppReportsProductsRouteImport.update({
  id: '/reports/products',
  path: '/reports/products',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsOutstandingRoute = AppReportsOutstandingRouteImport.update({
  id: '/reports/outstanding',
  path: '/reports/outstanding',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsOrdersRoute = AppReportsOrdersRouteImport.update({
  id: '/reports/orders',
  path: '/reports/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsInvoicesRoute = AppReportsInvoicesRouteImport.update({
  id: '/reports/invoices',
  path: '/reports/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsInventoryRoute = AppReportsInventoryRouteImport.update({
  id: '/reports/inventory',
  path: '/reports/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsGstRoute = AppReportsGstRouteImport.update({
  id: '/reports/gst',
  path: '/reports/gst',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsEmployeesRoute = AppReportsEmployeesRouteImport.update({
  id: '/reports/employees',
  path: '/reports/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsCustomersRoute = AppReportsCustomersRouteImport.update({
  id: '/reports/customers',
  path: '/reports/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsCollectionsRoute = AppReportsCollectionsRouteImport.update({
  id: '/reports/collections',
  path: '/reports/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsAmcRoute = AppReportsAmcRouteImport.update({
  id: '/reports/amc',
  path: '/reports/amc',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesInvoicesIndexRoute = AppSalesInvoicesIndexRouteImport.update({
  id: '/sales/invoices/',
  path: '/sales/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesEstimatesIndexRoute = AppSalesEstimatesIndexRouteImport.update({
  id: '/sales/estimates/',
  path: '/sales/estimates/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesInvoicesNewRoute = AppSalesInvoicesNewRouteImport.update({
  id: '/sales/invoices/new',
  path: '/sales/invoices/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesEstimatesNewRoute = AppSalesEstimatesNewRouteImport.update({
  id: '/sales/estimates/new',
  path: '/sales/estimates/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/select-branch': typeof SelectBranchRoute
  '/audit-log': typeof AppAuditLogRoute
  '/branches': typeof AppBranchesRoute
  '/companies': typeof AppCompaniesRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRoute
  '/inventory': typeof AppInventoryRoute
  '/invoices': typeof AppInvoicesRoute
  '/price-list': typeof AppPriceListRoute
  '/products': typeof PublicProductsRouteWithChildren
  '/quotations': typeof AppQuotationsRoute
  '/roles': typeof AppRolesRoute
  '/sales-orders': typeof AppSalesOrdersRoute
  '/service': typeof AppServiceRoute
  '/vendors': typeof AppVendorsRoute
  '/warranty-admin': typeof AppWarrantyAdminRoute
  '/about': typeof PublicAboutRoute
  '/compare': typeof PublicCompareRoute
  '/contact': typeof PublicContactRoute
  '/dealers': typeof PublicDealersRoute
  '/recommend': typeof PublicRecommendRoute
  '/rental-generators': typeof PublicRentalGeneratorsRoute
  '/service-request': typeof PublicServiceRequestRoute
  '/used-generators': typeof PublicUsedGeneratorsRoute
  '/warranty': typeof PublicWarrantyRoute
  '/reports/amc': typeof AppReportsAmcRoute
  '/reports/collections': typeof AppReportsCollectionsRoute
  '/reports/customers': typeof AppReportsCustomersRoute
  '/reports/employees': typeof AppReportsEmployeesRoute
  '/reports/gst': typeof AppReportsGstRoute
  '/reports/inventory': typeof AppReportsInventoryRoute
  '/reports/invoices': typeof AppReportsInvoicesRoute
  '/reports/orders': typeof AppReportsOrdersRoute
  '/reports/outstanding': typeof AppReportsOutstandingRoute
  '/reports/products': typeof AppReportsProductsRoute
  '/reports/purchases': typeof AppReportsPurchasesRoute
  '/reports/quotations': typeof AppReportsQuotationsRoute
  '/reports/sales': typeof AppReportsSalesRoute
  '/reports/service': typeof AppReportsServiceRoute
  '/reports/warranty': typeof AppReportsWarrantyRoute
  '/sales/credit-notes': typeof AppSalesCreditNotesRoute
  '/sales/debit-notes': typeof AppSalesDebitNotesRoute
  '/products/$id': typeof PublicProductsIdRoute
  '/reports/': typeof AppReportsIndexRoute
  '/sales/estimates/new': typeof AppSalesEstimatesNewRoute
  '/sales/invoices/new': typeof AppSalesInvoicesNewRoute
  '/sales/estimates/': typeof AppSalesEstimatesIndexRoute
  '/sales/invoices/': typeof AppSalesInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/select-branch': typeof SelectBranchRoute
  '/audit-log': typeof AppAuditLogRoute
  '/branches': typeof AppBranchesRoute
  '/companies': typeof AppCompaniesRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRoute
  '/inventory': typeof AppInventoryRoute
  '/invoices': typeof AppInvoicesRoute
  '/price-list': typeof AppPriceListRoute
  '/products': typeof PublicProductsRouteWithChildren
  '/quotations': typeof AppQuotationsRoute
  '/roles': typeof AppRolesRoute
  '/sales-orders': typeof AppSalesOrdersRoute
  '/service': typeof AppServiceRoute
  '/vendors': typeof AppVendorsRoute
  '/warranty-admin': typeof AppWarrantyAdminRoute
  '/about': typeof PublicAboutRoute
  '/compare': typeof PublicCompareRoute
  '/contact': typeof PublicContactRoute
  '/dealers': typeof PublicDealersRoute
  '/recommend': typeof PublicRecommendRoute
  '/rental-generators': typeof PublicRentalGeneratorsRoute
  '/service-request': typeof PublicServiceRequestRoute
  '/used-generators': typeof PublicUsedGeneratorsRoute
  '/warranty': typeof PublicWarrantyRoute
  '/reports/amc': typeof AppReportsAmcRoute
  '/reports/collections': typeof AppReportsCollectionsRoute
  '/reports/customers': typeof AppReportsCustomersRoute
  '/reports/employees': typeof AppReportsEmployeesRoute
  '/reports/gst': typeof AppReportsGstRoute
  '/reports/inventory': typeof AppReportsInventoryRoute
  '/reports/invoices': typeof AppReportsInvoicesRoute
  '/reports/orders': typeof AppReportsOrdersRoute
  '/reports/outstanding': typeof AppReportsOutstandingRoute
  '/reports/products': typeof AppReportsProductsRoute
  '/reports/purchases': typeof AppReportsPurchasesRoute
  '/reports/quotations': typeof AppReportsQuotationsRoute
  '/reports/sales': typeof AppReportsSalesRoute
  '/reports/service': typeof AppReportsServiceRoute
  '/reports/warranty': typeof AppReportsWarrantyRoute
  '/sales/credit-notes': typeof AppSalesCreditNotesRoute
  '/sales/debit-notes': typeof AppSalesDebitNotesRoute
  '/products/$id': typeof PublicProductsIdRoute
  '/reports': typeof AppReportsIndexRoute
  '/sales/estimates/new': typeof AppSalesEstimatesNewRoute
  '/sales/invoices/new': typeof AppSalesInvoicesNewRoute
  '/sales/estimates': typeof AppSalesEstimatesIndexRoute
  '/sales/invoices': typeof AppSalesInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/select-branch': typeof SelectBranchRoute
  '/_app/audit-log': typeof AppAuditLogRoute
  '/_app/branches': typeof AppBranchesRoute
  '/_app/companies': typeof AppCompaniesRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/price-list': typeof AppPriceListRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/quotations': typeof AppQuotationsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/sales-orders': typeof AppSalesOrdersRoute
  '/_app/service': typeof AppServiceRoute
  '/_app/vendors': typeof AppVendorsRoute
  '/_app/warranty-admin': typeof AppWarrantyAdminRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/compare': typeof PublicCompareRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/dealers': typeof PublicDealersRoute
  '/_public/products': typeof PublicProductsRouteWithChildren
  '/_public/recommend': typeof PublicRecommendRoute
  '/_public/rental-generators': typeof PublicRentalGeneratorsRoute
  '/_public/service-request': typeof PublicServiceRequestRoute
  '/_public/used-generators': typeof PublicUsedGeneratorsRoute
  '/_public/warranty': typeof PublicWarrantyRoute
  '/_public/': typeof PublicIndexRoute
  '/_app/reports/amc': typeof AppReportsAmcRoute
  '/_app/reports/collections': typeof AppReportsCollectionsRoute
  '/_app/reports/customers': typeof AppReportsCustomersRoute
  '/_app/reports/employees': typeof AppReportsEmployeesRoute
  '/_app/reports/gst': typeof AppReportsGstRoute
  '/_app/reports/inventory': typeof AppReportsInventoryRoute
  '/_app/reports/invoices': typeof AppReportsInvoicesRoute
  '/_app/reports/orders': typeof AppReportsOrdersRoute
  '/_app/reports/outstanding': typeof AppReportsOutstandingRoute
  '/_app/reports/products': typeof AppReportsProductsRoute
  '/_app/reports/purchases': typeof AppReportsPurchasesRoute
  '/_app/reports/quotations': typeof AppReportsQuotationsRoute
  '/_app/reports/sales': typeof AppReportsSalesRoute
  '/_app/reports/service': typeof AppReportsServiceRoute
  '/_app/reports/warranty': typeof AppReportsWarrantyRoute
  '/_app/sales/credit-notes': typeof AppSalesCreditNotesRoute
  '/_app/sales/debit-notes': typeof AppSalesDebitNotesRoute
  '/_public/products/$id': typeof PublicProductsIdRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/sales/estimates/new': typeof AppSalesEstimatesNewRoute
  '/_app/sales/invoices/new': typeof AppSalesInvoicesNewRoute
  '/_app/sales/estimates/': typeof AppSalesEstimatesIndexRoute
  '/_app/sales/invoices/': typeof AppSalesInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/select-branch'
    | '/audit-log'
    | '/branches'
    | '/companies'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/inventory'
    | '/invoices'
    | '/price-list'
    | '/products'
    | '/quotations'
    | '/roles'
    | '/sales-orders'
    | '/service'
    | '/vendors'
    | '/warranty-admin'
    | '/about'
    | '/compare'
    | '/contact'
    | '/dealers'
    | '/recommend'
    | '/rental-generators'
    | '/service-request'
    | '/used-generators'
    | '/warranty'
    | '/reports/amc'
    | '/reports/collections'
    | '/reports/customers'
    | '/reports/employees'
    | '/reports/gst'
    | '/reports/inventory'
    | '/reports/invoices'
    | '/reports/orders'
    | '/reports/outstanding'
    | '/reports/products'
    | '/reports/purchases'
    | '/reports/quotations'
    | '/reports/sales'
    | '/reports/service'
    | '/reports/warranty'
    | '/sales/credit-notes'
    | '/sales/debit-notes'
    | '/products/$id'
    | '/reports/'
    | '/sales/estimates/new'
    | '/sales/invoices/new'
    | '/sales/estimates/'
    | '/sales/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/select-branch'
    | '/audit-log'
    | '/branches'
    | '/companies'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/inventory'
    | '/invoices'
    | '/price-list'
    | '/products'
    | '/quotations'
    | '/roles'
    | '/sales-orders'
    | '/service'
    | '/vendors'
    | '/warranty-admin'
    | '/about'
    | '/compare'
    | '/contact'
    | '/dealers'
    | '/recommend'
    | '/rental-generators'
    | '/service-request'
    | '/used-generators'
    | '/warranty'
    | '/reports/amc'
    | '/reports/collections'
    | '/reports/customers'
    | '/reports/employees'
    | '/reports/gst'
    | '/reports/inventory'
    | '/reports/invoices'
    | '/reports/orders'
    | '/reports/outstanding'
    | '/reports/products'
    | '/reports/purchases'
    | '/reports/quotations'
    | '/reports/sales'
    | '/reports/service'
    | '/reports/warranty'
    | '/sales/credit-notes'
    | '/sales/debit-notes'
    | '/products/$id'
    | '/reports'
    | '/sales/estimates/new'
    | '/sales/invoices/new'
    | '/sales/estimates'
    | '/sales/invoices'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/admin'
    | '/login'
    | '/select-branch'
    | '/_app/audit-log'
    | '/_app/branches'
    | '/_app/companies'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/employees'
    | '/_app/inventory'
    | '/_app/invoices'
    | '/_app/price-list'
    | '/_app/products'
    | '/_app/quotations'
    | '/_app/roles'
    | '/_app/sales-orders'
    | '/_app/service'
    | '/_app/vendors'
    | '/_app/warranty-admin'
    | '/_public/about'
    | '/_public/compare'
    | '/_public/contact'
    | '/_public/dealers'
    | '/_public/products'
    | '/_public/recommend'
    | '/_public/rental-generators'
    | '/_public/service-request'
    | '/_public/used-generators'
    | '/_public/warranty'
    | '/_public/'
    | '/_app/reports/amc'
    | '/_app/reports/collections'
    | '/_app/reports/customers'
    | '/_app/reports/employees'
    | '/_app/reports/gst'
    | '/_app/reports/inventory'
    | '/_app/reports/invoices'
    | '/_app/reports/orders'
    | '/_app/reports/outstanding'
    | '/_app/reports/products'
    | '/_app/reports/purchases'
    | '/_app/reports/quotations'
    | '/_app/reports/sales'
    | '/_app/reports/service'
    | '/_app/reports/warranty'
    | '/_app/sales/credit-notes'
    | '/_app/sales/debit-notes'
    | '/_public/products/$id'
    | '/_app/reports/'
    | '/_app/sales/estimates/new'
    | '/_app/sales/invoices/new'
    | '/_app/sales/estimates/'
    | '/_app/sales/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  SelectBranchRoute: typeof SelectBranchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-branch': {
      id: '/select-branch'
      path: '/select-branch'
      fullPath: '/select-branch'
      preLoaderRoute: typeof SelectBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/warranty': {
      id: '/_public/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof PublicWarrantyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/used-generators': {
      id: '/_public/used-generators'
      path: '/used-generators'
      fullPath: '/used-generators'
      preLoaderRoute: typeof PublicUsedGeneratorsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/service-request': {
      id: '/_public/service-request'
      path: '/service-request'
      fullPath: '/service-request'
      preLoaderRoute: typeof PublicServiceRequestRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/rental-generators': {
      id: '/_public/rental-generators'
      path: '/rental-generators'
      fullPath: '/rental-generators'
      preLoaderRoute: typeof PublicRentalGeneratorsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/recommend': {
      id: '/_public/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof PublicRecommendRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products': {
      id: '/_public/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof PublicProductsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/dealers': {
      id: '/_public/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof PublicDealersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/compare': {
      id: '/_public/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof PublicCompareRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/warranty-admin': {
      id: '/_app/warranty-admin'
      path: '/warranty-admin'
      fullPath: '/warranty-admin'
      preLoaderRoute: typeof AppWarrantyAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors': {
      id: '/_app/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service': {
      id: '/_app/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof AppServiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-orders': {
      id: '/_app/sales-orders'
      path: '/sales-orders'
      fullPath: '/sales-orders'
      preLoaderRoute: typeof AppSalesOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations': {
      id: '/_app/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/price-list': {
      id: '/_app/price-list'
      path: '/price-list'
      fullPath: '/price-list'
      preLoaderRoute: typeof AppPriceListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches': {
      id: '/_app/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-log': {
      id: '/_app/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AppAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/products/$id': {
      id: '/_public/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof PublicProductsIdRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_app/sales/debit-notes': {
      id: '/_app/sales/debit-notes'
      path: '/sales/debit-notes'
      fullPath: '/sales/debit-notes'
      preLoaderRoute: typeof AppSalesDebitNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/credit-notes': {
      id: '/_app/sales/credit-notes'
      path: '/sales/credit-notes'
      fullPath: '/sales/credit-notes'
      preLoaderRoute: typeof AppSalesCreditNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/warranty': {
      id: '/_app/reports/warranty'
      path: '/reports/warranty'
      fullPath: '/reports/warranty'
      preLoaderRoute: typeof AppReportsWarrantyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/service': {
      id: '/_app/reports/service'
      path: '/reports/service'
      fullPath: '/reports/service'
      preLoaderRoute: typeof AppReportsServiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/sales': {
      id: '/_app/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AppReportsSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/quotations': {
      id: '/_app/reports/quotations'
      path: '/reports/quotations'
      fullPath: '/reports/quotations'
      preLoaderRoute: typeof AppReportsQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/purchases': {
      id: '/_app/reports/purchases'
      path: '/reports/purchases'
      fullPath: '/reports/purchases'
      preLoaderRoute: typeof AppReportsPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/products': {
      id: '/_app/reports/products'
      path: '/reports/products'
      fullPath: '/reports/products'
      preLoaderRoute: typeof AppReportsProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/outstanding': {
      id: '/_app/reports/outstanding'
      path: '/reports/outstanding'
      fullPath: '/reports/outstanding'
      preLoaderRoute: typeof AppReportsOutstandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/orders': {
      id: '/_app/reports/orders'
      path: '/reports/orders'
      fullPath: '/reports/orders'
      preLoaderRoute: typeof AppReportsOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/invoices': {
      id: '/_app/reports/invoices'
      path: '/reports/invoices'
      fullPath: '/reports/invoices'
      preLoaderRoute: typeof AppReportsInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/inventory': {
      id: '/_app/reports/inventory'
      path: '/reports/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof AppReportsInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/gst': {
      id: '/_app/reports/gst'
      path: '/reports/gst'
      fullPath: '/reports/gst'
      preLoaderRoute: typeof AppReportsGstRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/employees': {
      id: '/_app/reports/employees'
      path: '/reports/employees'
      fullPath: '/reports/employees'
      preLoaderRoute: typeof AppReportsEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/customers': {
      id: '/_app/reports/customers'
      path: '/reports/customers'
      fullPath: '/reports/customers'
      preLoaderRoute: typeof AppReportsCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/collections': {
      id: '/_app/reports/collections'
      path: '/reports/collections'
      fullPath: '/reports/collections'
      preLoaderRoute: typeof AppReportsCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/amc': {
      id: '/_app/reports/amc'
      path: '/reports/amc'
      fullPath: '/reports/amc'
      preLoaderRoute: typeof AppReportsAmcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/invoices/': {
      id: '/_app/sales/invoices/'
      path: '/sales/invoices'
      fullPath: '/sales/invoices/'
      preLoaderRoute: typeof AppSalesInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/estimates/': {
      id: '/_app/sales/estimates/'
      path: '/sales/estimates'
      fullPath: '/sales/estimates/'
      preLoaderRoute: typeof AppSalesEstimatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/invoices/new': {
      id: '/_app/sales/invoices/new'
      path: '/sales/invoices/new'
      fullPath: '/sales/invoices/new'
      preLoaderRoute: typeof AppSalesInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/estimates/new': {
      id: '/_app/sales/estimates/new'
      path: '/sales/estimates/new'
      fullPath: '/sales/estimates/new'
      preLoaderRoute: typeof AppSalesEstimatesNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditLogRoute: typeof AppAuditLogRoute
  AppBranchesRoute: typeof AppBranchesRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppPriceListRoute: typeof AppPriceListRoute
  AppProductsRoute: typeof AppProductsRoute
  AppQuotationsRoute: typeof AppQuotationsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSalesOrdersRoute: typeof AppSalesOrdersRoute
  AppServiceRoute: typeof AppServiceRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppWarrantyAdminRoute: typeof AppWarrantyAdminRoute
  AppReportsAmcRoute: typeof AppReportsAmcRoute
  AppReportsCollectionsRoute: typeof AppReportsCollectionsRoute
  AppReportsCustomersRoute: typeof AppReportsCustomersRoute
  AppReportsEmployeesRoute: typeof AppReportsEmployeesRoute
  AppReportsGstRoute: typeof AppReportsGstRoute
  AppReportsInventoryRoute: typeof AppReportsInventoryRoute
  AppReportsInvoicesRoute: typeof AppReportsInvoicesRoute
  AppReportsOrdersRoute: typeof AppReportsOrdersRoute
  AppReportsOutstandingRoute: typeof AppReportsOutstandingRoute
  AppReportsProductsRoute: typeof AppReportsProductsRoute
  AppReportsPurchasesRoute: typeof AppReportsPurchasesRoute
  AppReportsQuotationsRoute: typeof AppReportsQuotationsRoute
  AppReportsSalesRoute: typeof AppReportsSalesRoute
  AppReportsServiceRoute: typeof AppReportsServiceRoute
  AppReportsWarrantyRoute: typeof AppReportsWarrantyRoute
  AppSalesCreditNotesRoute: typeof AppSalesCreditNotesRoute
  AppSalesDebitNotesRoute: typeof AppSalesDebitNotesRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSalesEstimatesNewRoute: typeof AppSalesEstimatesNewRoute
  AppSalesInvoicesNewRoute: typeof AppSalesInvoicesNewRoute
  AppSalesEstimatesIndexRoute: typeof AppSalesEstimatesIndexRoute
  AppSalesInvoicesIndexRoute: typeof AppSalesInvoicesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditLogRoute: AppAuditLogRoute,
  AppBranchesRoute: AppBranchesRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppPriceListRoute: AppPriceListRoute,
  AppProductsRoute: AppProductsRoute,
  AppQuotationsRoute: AppQuotationsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSalesOrdersRoute: AppSalesOrdersRoute,
  AppServiceRoute: AppServiceRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppWarrantyAdminRoute: AppWarrantyAdminRoute,
  AppReportsAmcRoute: AppReportsAmcRoute,
  AppReportsCollectionsRoute: AppReportsCollectionsRoute,
  AppReportsCustomersRoute: AppReportsCustomersRoute,
  AppReportsEmployeesRoute: AppReportsEmployeesRoute,
  AppReportsGstRoute: AppReportsGstRoute,
  AppReportsInventoryRoute: AppReportsInventoryRoute,
  AppReportsInvoicesRoute: AppReportsInvoicesRoute,
  AppReportsOrdersRoute: AppReportsOrdersRoute,
  AppReportsOutstandingRoute: AppReportsOutstandingRoute,
  AppReportsProductsRoute: AppReportsProductsRoute,
  AppReportsPurchasesRoute: AppReportsPurchasesRoute,
  AppReportsQuotationsRoute: AppReportsQuotationsRoute,
  AppReportsSalesRoute: AppReportsSalesRoute,
  AppReportsServiceRoute: AppReportsServiceRoute,
  AppReportsWarrantyRoute: AppReportsWarrantyRoute,
  AppSalesCreditNotesRoute: AppSalesCreditNotesRoute,
  AppSalesDebitNotesRoute: AppSalesDebitNotesRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSalesEstimatesNewRoute: AppSalesEstimatesNewRoute,
  AppSalesInvoicesNewRoute: AppSalesInvoicesNewRoute,
  AppSalesEstimatesIndexRoute: AppSalesEstimatesIndexRoute,
  AppSalesInvoicesIndexRoute: AppSalesInvoicesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicProductsRouteChildren {
  PublicProductsIdRoute: typeof PublicProductsIdRoute
}

const PublicProductsRouteChildren: PublicProductsRouteChildren = {
  PublicProductsIdRoute: PublicProductsIdRoute,
}

const PublicProductsRouteWithChildren = PublicProductsRoute._addFileChildren(
  PublicProductsRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicCompareRoute: typeof PublicCompareRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicDealersRoute: typeof PublicDealersRoute
  PublicProductsRoute: typeof PublicProductsRouteWithChildren
  PublicRecommendRoute: typeof PublicRecommendRoute
  PublicRentalGeneratorsRoute: typeof PublicRentalGeneratorsRoute
  PublicServiceRequestRoute: typeof PublicServiceRequestRoute
  PublicUsedGeneratorsRoute: typeof PublicUsedGeneratorsRoute
  PublicWarrantyRoute: typeof PublicWarrantyRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicCompareRoute: PublicCompareRoute,
  PublicContactRoute: PublicContactRoute,
  PublicDealersRoute: PublicDealersRoute,
  PublicProductsRoute: PublicProductsRouteWithChildren,
  PublicRecommendRoute: PublicRecommendRoute,
  PublicRentalGeneratorsRoute: PublicRentalGeneratorsRoute,
  PublicServiceRequestRoute: PublicServiceRequestRoute,
  PublicUsedGeneratorsRoute: PublicUsedGeneratorsRoute,
  PublicWarrantyRoute: PublicWarrantyRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  SelectBranchRoute: SelectBranchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
