/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicWarrantyRouteImport } from './routes/_public/warranty'
import { Route as PublicUsedGeneratorsRouteImport } from './routes/_public/used-generators'
import { Route as PublicServiceRequestRouteImport } from './routes/_public/service-request'
import { Route as PublicRentalGeneratorsRouteImport } from './routes/_public/rental-generators'
import { Route as PublicRecommendRouteImport } from './routes/_public/recommend'
import { Route as PublicProductsRouteImport } from './routes/_public/products'
import { Route as PublicDealersRouteImport } from './routes/_public/dealers'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicCompareRouteImport } from './routes/_public/compare'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as AppWarrantyAdminRouteImport } from './routes/_app/warranty-admin'
import { Route as AppVendorsRouteImport } from './routes/_app/vendors'
import { Route as AppServiceRouteImport } from './routes/_app/service'
import { Route as AppSalesOrdersRouteImport } from './routes/_app/sales-orders'
import { Route as AppRolesRouteImport } from './routes/_app/roles'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppQuotationsRouteImport } from './routes/_app/quotations'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppEmployeesRouteImport } from './routes/_app/employees'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as PublicProductsIdRouteImport } from './routes/_public/products.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicWarrantyRoute = PublicWarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => PublicRoute,
} as any)
const PublicUsedGeneratorsRoute = PublicUsedGeneratorsRouteImport.update({
  id: '/used-generators',
  path: '/used-generators',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServiceRequestRoute = PublicServiceRequestRouteImport.update({
  id: '/service-request',
  path: '/service-request',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRentalGeneratorsRoute = PublicRentalGeneratorsRouteImport.update({
  id: '/rental-generators',
  path: '/rental-generators',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRecommendRoute = PublicRecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsRoute = PublicProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDealersRoute = PublicDealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCompareRoute = PublicCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AppWarrantyAdminRoute = AppWarrantyAdminRouteImport.update({
  id: '/warranty-admin',
  path: '/warranty-admin',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceRoute = AppServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersRoute = AppSalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const PublicProductsIdRoute = PublicProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRoute
  '/inventory': typeof AppInventoryRoute
  '/invoices': typeof AppInvoicesRoute
  '/products': typeof PublicProductsRouteWithChildren
  '/quotations': typeof AppQuotationsRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/sales-orders': typeof AppSalesOrdersRoute
  '/service': typeof AppServiceRoute
  '/vendors': typeof AppVendorsRoute
  '/warranty-admin': typeof AppWarrantyAdminRoute
  '/about': typeof PublicAboutRoute
  '/compare': typeof PublicCompareRoute
  '/contact': typeof PublicContactRoute
  '/dealers': typeof PublicDealersRoute
  '/recommend': typeof PublicRecommendRoute
  '/rental-generators': typeof PublicRentalGeneratorsRoute
  '/service-request': typeof PublicServiceRequestRoute
  '/used-generators': typeof PublicUsedGeneratorsRoute
  '/warranty': typeof PublicWarrantyRoute
  '/products/$id': typeof PublicProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRoute
  '/inventory': typeof AppInventoryRoute
  '/invoices': typeof AppInvoicesRoute
  '/products': typeof PublicProductsRouteWithChildren
  '/quotations': typeof AppQuotationsRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/sales-orders': typeof AppSalesOrdersRoute
  '/service': typeof AppServiceRoute
  '/vendors': typeof AppVendorsRoute
  '/warranty-admin': typeof AppWarrantyAdminRoute
  '/about': typeof PublicAboutRoute
  '/compare': typeof PublicCompareRoute
  '/contact': typeof PublicContactRoute
  '/dealers': typeof PublicDealersRoute
  '/recommend': typeof PublicRecommendRoute
  '/rental-generators': typeof PublicRentalGeneratorsRoute
  '/service-request': typeof PublicServiceRequestRoute
  '/used-generators': typeof PublicUsedGeneratorsRoute
  '/warranty': typeof PublicWarrantyRoute
  '/products/$id': typeof PublicProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/quotations': typeof AppQuotationsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/sales-orders': typeof AppSalesOrdersRoute
  '/_app/service': typeof AppServiceRoute
  '/_app/vendors': typeof AppVendorsRoute
  '/_app/warranty-admin': typeof AppWarrantyAdminRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/compare': typeof PublicCompareRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/dealers': typeof PublicDealersRoute
  '/_public/products': typeof PublicProductsRouteWithChildren
  '/_public/recommend': typeof PublicRecommendRoute
  '/_public/rental-generators': typeof PublicRentalGeneratorsRoute
  '/_public/service-request': typeof PublicServiceRequestRoute
  '/_public/used-generators': typeof PublicUsedGeneratorsRoute
  '/_public/warranty': typeof PublicWarrantyRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/products/$id': typeof PublicProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/inventory'
    | '/invoices'
    | '/products'
    | '/quotations'
    | '/reports'
    | '/roles'
    | '/sales-orders'
    | '/service'
    | '/vendors'
    | '/warranty-admin'
    | '/about'
    | '/compare'
    | '/contact'
    | '/dealers'
    | '/recommend'
    | '/rental-generators'
    | '/service-request'
    | '/used-generators'
    | '/warranty'
    | '/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/inventory'
    | '/invoices'
    | '/products'
    | '/quotations'
    | '/reports'
    | '/roles'
    | '/sales-orders'
    | '/service'
    | '/vendors'
    | '/warranty-admin'
    | '/about'
    | '/compare'
    | '/contact'
    | '/dealers'
    | '/recommend'
    | '/rental-generators'
    | '/service-request'
    | '/used-generators'
    | '/warranty'
    | '/products/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/admin'
    | '/login'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/employees'
    | '/_app/inventory'
    | '/_app/invoices'
    | '/_app/products'
    | '/_app/quotations'
    | '/_app/reports'
    | '/_app/roles'
    | '/_app/sales-orders'
    | '/_app/service'
    | '/_app/vendors'
    | '/_app/warranty-admin'
    | '/_public/about'
    | '/_public/compare'
    | '/_public/contact'
    | '/_public/dealers'
    | '/_public/products'
    | '/_public/recommend'
    | '/_public/rental-generators'
    | '/_public/service-request'
    | '/_public/used-generators'
    | '/_public/warranty'
    | '/_public/'
    | '/_public/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/warranty': {
      id: '/_public/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof PublicWarrantyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/used-generators': {
      id: '/_public/used-generators'
      path: '/used-generators'
      fullPath: '/used-generators'
      preLoaderRoute: typeof PublicUsedGeneratorsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/service-request': {
      id: '/_public/service-request'
      path: '/service-request'
      fullPath: '/service-request'
      preLoaderRoute: typeof PublicServiceRequestRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/rental-generators': {
      id: '/_public/rental-generators'
      path: '/rental-generators'
      fullPath: '/rental-generators'
      preLoaderRoute: typeof PublicRentalGeneratorsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/recommend': {
      id: '/_public/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof PublicRecommendRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products': {
      id: '/_public/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof PublicProductsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/dealers': {
      id: '/_public/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof PublicDealersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/compare': {
      id: '/_public/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof PublicCompareRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/warranty-admin': {
      id: '/_app/warranty-admin'
      path: '/warranty-admin'
      fullPath: '/warranty-admin'
      preLoaderRoute: typeof AppWarrantyAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors': {
      id: '/_app/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service': {
      id: '/_app/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof AppServiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-orders': {
      id: '/_app/sales-orders'
      path: '/sales-orders'
      fullPath: '/sales-orders'
      preLoaderRoute: typeof AppSalesOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations': {
      id: '/_app/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/products/$id': {
      id: '/_public/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof PublicProductsIdRouteImport
      parentRoute: typeof PublicProductsRoute
    }
  }
}

interface AppRouteChildren {
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppProductsRoute: typeof AppProductsRoute
  AppQuotationsRoute: typeof AppQuotationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSalesOrdersRoute: typeof AppSalesOrdersRoute
  AppServiceRoute: typeof AppServiceRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppWarrantyAdminRoute: typeof AppWarrantyAdminRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppProductsRoute: AppProductsRoute,
  AppQuotationsRoute: AppQuotationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSalesOrdersRoute: AppSalesOrdersRoute,
  AppServiceRoute: AppServiceRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppWarrantyAdminRoute: AppWarrantyAdminRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicProductsRouteChildren {
  PublicProductsIdRoute: typeof PublicProductsIdRoute
}

const PublicProductsRouteChildren: PublicProductsRouteChildren = {
  PublicProductsIdRoute: PublicProductsIdRoute,
}

const PublicProductsRouteWithChildren = PublicProductsRoute._addFileChildren(
  PublicProductsRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicCompareRoute: typeof PublicCompareRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicDealersRoute: typeof PublicDealersRoute
  PublicProductsRoute: typeof PublicProductsRouteWithChildren
  PublicRecommendRoute: typeof PublicRecommendRoute
  PublicRentalGeneratorsRoute: typeof PublicRentalGeneratorsRoute
  PublicServiceRequestRoute: typeof PublicServiceRequestRoute
  PublicUsedGeneratorsRoute: typeof PublicUsedGeneratorsRoute
  PublicWarrantyRoute: typeof PublicWarrantyRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicCompareRoute: PublicCompareRoute,
  PublicContactRoute: PublicContactRoute,
  PublicDealersRoute: PublicDealersRoute,
  PublicProductsRoute: PublicProductsRouteWithChildren,
  PublicRecommendRoute: PublicRecommendRoute,
  PublicRentalGeneratorsRoute: PublicRentalGeneratorsRoute,
  PublicServiceRequestRoute: PublicServiceRequestRoute,
  PublicUsedGeneratorsRoute: PublicUsedGeneratorsRoute,
  PublicWarrantyRoute: PublicWarrantyRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
